site_name: My Docs

plugins:
- search
- extract_listings:
    listings_file: plugin/all-listings.md
    placeholder: CUSTOM_PLACEHOLDER_FOR_THE_LISTINGS_PLUGIN
    javascript_search_file: listing-search.js

theme: material
site_url: https://example.six-two.dev/

# https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
