site_name: My Docs
use_directory_urls: true

plugins:
- search
- extract_listings:
    listings_file: plugin/all-listings.md
    placeholder: CUSTOM_PLACEHOLDER_FOR_THE_LISTINGS_PLUGIN
    javascript_search_file: some-path/listing-search.js
    default_css: true
    offline: false

theme: material
site_url: https://mkdocs-extract-listings-plugin.six-two.dev/

# https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
